name: Build source RPM

on: create

jobs:
  source:
    name: Source
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel twine babel

    - name: Build catalogs
      env:
        poeditor_api_token: ${{ secrets.POEDITOR_API_TOKEN }}
      run: |
        ./scripts/poedit.sh download

    - name: Build binaries
      env:
        BUILD_DIR: build/rpm
      run: |
        mkdir srpm
        python3 setup.py bdist_rpm --dist-dir=srpm/ --source-only

    - name: Upload to GitHub Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: srpm/
        GITHUB_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
