name: Stricter python linting on changes only

on: [pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8

    - name: Fetch pull request
      run: |
        git fetch origin ${GITHUB_REF%/merge}/head

    - name: Lint changes with flake8
      run: |
        # Reduced list of ignores, applied on the changed lines only
        git diff FETCH_HEAD -U0 | flake8 --diff --count --show-source --statistics --ignore=D107,D200,D210,D413,E251,E302,E303,W504
